name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: open-telemetry-1000
  REGION: us-central1
  SERVICE: otel-mart-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 1. Authenticate to Google Cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 2. Build and Push Container
      - name: Build and Push
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/dilly3-repo/otel-mart-api:latest -f build/Dockerfile .
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/dilly3-repo/otel-mart-api:latest

      # 3. Deploy to Cloud Run
      # - name: Deploy
      #   uses: 'google-github-actions/deploy-cloudrun@v1'
      #   with:
      #     service: ${{ env.SERVICE }}
      #     image: "us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/dilly3-repo/otel-mart-api:latest" 
      #     region: ${{ env.REGION }}
      #     env_vars: |
      #       APP_ENV=production
      #       GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }}
      #       DB_HOST=${{ secrets.DB_HOST }}
      #       DB_PORT=5432
      #       DB_NAME=otel-mart
      #       DB_USER=otel-user
      #       DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: ./deploy/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./deploy/terraform
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          cat > override.auto.tfvars <<EOF
          project_id = "${{ env.PROJECT_ID }}"
          region = "${{ env.REGION }}"
          DB_PASSWORD = "${{ secrets.DB_PASSWORD }}"
          DB_HOST = "${{ secrets.DB_HOST }}"
          EOF
          cat override.auto.tfvars
          terraform import google_sql_database_instance.otel-mart-db-instance projects/open-telemetry-1000/instances/otel-mart-db-instance
          terraform import google_sql_database.otel-mart-db projects/open-telemetry-1000/instances/otel-mart-db-instance/databases/otel-mart
          terraform import google_sql_user.otel-mart-db-user projects/open-telemetry-1000/instances/otel-mart-db-instance/users/otel-user
          terraform apply -auto-approve